apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: teamflow.local
    http:
      paths:

      # ðŸ”¹ Frontend (React)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

      # ðŸ”¹ API EMPLOYEE
      - path: /employees
        pathType: Prefix
        backend:
          service:
            name: employee-service
            port:
              number: 80

      # ðŸ”¹ API PAYROLL
      - path: /payroll
        pathType: Prefix
        backend:
          service:
            name: payroll-service
            port:
              number: 80

      # ðŸ”¹ API DEPARTMENT
      - path: /departments
        pathType: Prefix
        backend:
          service:
            name: department-service
            port:
              number: 80

