name: TeamFlow CI/CD

on:
  push:
    branches: ["main"]

jobs:

  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Employee Service
      uses: docker/build-push-action@v4
      with:
        context: ./microservices/employee
        push: true
        tags: nourgharby/teamflow-employee:latest

    - name: Build & Push Payroll Service
      uses: docker/build-push-action@v4
      with:
        context: ./microservices/payroll
        push: true
        tags: nourgharby/teamflow-payroll:latest

    - name: Build & Push Department Service
      uses: docker/build-push-action@v4
      with:
        context: ./microservices/department
        push: true
        tags: nourgharby/teamflow-department:latest

    - name: Build & Push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./teamflow-react-frontend
        push: true
        tags: nourgharby/teamflow-frontend:latest


  deploy:
    name: Deploy to Minikube VM via SSH
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into VM and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VM_SSH_HOST }}      # 192.168.191.188
        username: ${{ secrets.VM_SSH_USER }}  # teamflow
        key: ${{ secrets.SSH_PRIVATE_KEY }}   # your PRIVATE KEY stored as secret
        port: 22
        script: |
          echo "CONNECTED TO VM"
          cd ~/teamflow

          echo "Applying Kubernetes manifests..."
          kubectl apply -f microservices/employee/
          kubectl apply -f microservices/payroll/
          kubectl apply -f microservices/department/
          kubectl apply -f microservices/frontend/

          echo "Restarting deployments..."
          kubectl rollout restart deployment employee-deployment
          kubectl rollout restart deployment department-deployment
          kubectl rollout restart deployment payroll-deployment
          kubectl rollout restart deployment frontend-deployment

          echo "CI/CD DEPLOYMENT DONE SUCCESSFULLY."

